"""Active MVP mapping and calibration configuration (PCA4 ridge + keyboard15)."""

from __future__ import annotations

MAPPER_ID = "pca4_baseline_v1"
ACTIVE_MAPPER = "pca4_baseline"
CALIBRATION_MODE = "keyboard15"

ALPHA_GRID: tuple[float, ...] = (0.15, 0.3, 0.5, 1.0, 10.0, 50.0, 100.0, 200.0, 400.0)
ALPHA_SELECT_LOOCV_TOL_PX = 5.0
MIN_ALPHA = 0.15
APPLY_ROW_Y_BIAS = False

FEATURE_SMOOTHER_ALPHA = 0.28
GAZE_SMOOTHER_ALPHA = 0.35

MAX_LOOCV_RMS_PX = 95.0
MAX_TARGET_LOOCV_PX = 110.0
MAX_TRAIN_ERROR_PX = 60.0
HALF_KEY_HEIGHT_PX = 34.0
MAX_VALIDATION_ERROR_PX = 80.0
MAX_OFF_SCREEN_LOOCV = 0
MIN_SCREEN_Y_AVG_V_CORR = 0.55
MIN_CATASTROPHIC_SCREEN_Y_AVG_V_CORR = 0.15
MAX_SINGLE_TARGET_TRAIN_PX = 55.0

CALIB_HEAD_DRIFT_FACE_XY = 0.008
CALIB_HEAD_DRIFT_EYE_H = 0.003
MAX_HEAD_DRIFT_EYE_H = 0.0045
MIN_AVG_V_ROW_SEPARATION = 0.025

# Back-compat aliases used by run summaries and logs.
TYPING_CANDIDATE_ID = MAPPER_ID
